# Generated by Django 3.2.5 on 2021-07-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcuser',
            table='fastcampus_fcuser',
        ),
    ]
