# Generated by Django 3.2.5 on 2021-07-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_user', '0002_alter_fcuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
